CREATE TABLE `springcloud`.`user` (
  `id` BIGINT NOT NULL,
  `USERNAME` VARCHAR(50) NULL,
  `PASSWORD` VARCHAR(50) NULL,
  `AGE` INT NULL,
  `BALANCE` DECIMAL(20) NULL,
  PRIMARY KEY (`id`));
