server:
  port: 8003
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    
zuul:
  sensitive-headers: Cookie", "Set-Cookie", "Authorization
  ignore-security-headers: true
  routes:
    user:
      service-id: user
      path: /user/**
#      strip-prefix: false # 局部
    cinema:
      service-id: cinema
      path: /cinema/**
    movie:
      service-id: movie
      path: /movie/**
    legacy: /** # 除了已经配置的，剩下的路由路径
  prefix: /api 

management:
  endpoints:
    web:
      exposure:
        include: health,info,routes
