server:
  port: 7903
spring:
  application:
    name: microservices-consumer-movie
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    ip-address: true
    
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
feign.hystrix.enabled: true