server:
  port: 8000
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/liaoqichao/movie-config
          search-paths:
          - user
          - cinema
          - movie
  security:
    user:
      name: user
      password: 123
eureka:
  client:
    service-url:
      defautlZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true