# 第一段共用配置
spring:
  application:
    name: eureka-server-cluster
# hosts 文件配置127.0.0.1 对应到peer1 peer2 peer3

--- 
spring:
  profiles: 
    peer1
server:
  port: 8761
eureka:
  client:
    service-url:
      defualtZone: http://peer2:8762/eureka/,http://peer3:8763/eureka/
  instance:
    metadata-map:
      zone: myzone # eureka自己自带的metadata
      demo8: this is demo8 # 自定义的元数据
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: peer1 # 指定主机名
    
---
spring:
  profiles: 
    peer2
server:
  port: 8762
eureka:
  client:
    service-url:
      defualtZone: http://peer1:8761/eureka/,http://peer3:8763/eureka/
  instance:
    metadata-map:
      zone: myzone # eureka自己自带的metadata
      demo8: this is demo8 # 自定义的元数据
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  hostname: peer2

---    
spring:
  profiles: 
    peer3
server:
  port: 8763
eureka:
  client:
    service-url:
      defualtZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  instance:
    metadata-map:
      zone: myzone # eureka自己自带的metadata
      demo8: this is demo8 # 自定义的元数据
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    hostname: peer3