spring:
  application:
    name: microservice-sidecar
server:
  port: 8070
eureka:
  client:
    healthcheck:
      enabled: true 
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
    
sidecar:
  port: 8060 # 指定异构为服务的端口
  health-uri: http://localhost:8060/health.json # 指定health指标
    