server:
  port: 7902
spring:
  application:
    name: movie
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 17902
logging:
  level:
    root : INFO
    lqc.demo.springcloud.*: trace # 改成你的mapper文件所在包路径