management:
  health:
    mail:
      enabled: false

eureka:
  client:
    healthcheck:
      enabled: true 
    service-url:
#      defaultZone: http://user:psw123@localhost:8761/eureka 
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    # 默认是         主机名:应用名:端口
    # 修改为         应用名:端口
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
server:
  port: 7900

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springcloud?serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    dbcp2:
      max-idle: 8
      max-total: 20
      min-idle: 8
      initial-size: 10
  application:
    name: microservices-provider-user # 名称建议用小写
mybatis:

  mapper-locations:
  - classpath:mybatis/*/mapper/*Mapper.xml

# 打印日志方法2
logging:
  level:
    root : INFO
    lqc.demo.springcloud.*: trace # 改成你的mapper文件所在包路径
  
  
