server:
  port: 7900
spring:
  application:
    name: user
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 17900
logging:
  level:
    root : INFO
    lqc.demo.springcloud.*: trace # 改成你的mapper文件所在包路径
