server:
  port: 7901
eureka:
  healcheck:
    enabled: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.server_id:${server.port}}
spring:
  application:
    name: microservices-consumer-movie
    
# 命令执行超时时间，默认1秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000