eureka:
  client:
    healthcheck:
      enabled: true
    service-url: 
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
server:
  port: 7901
spring:
  application:
    name: microservices-consumer-movie
#    name: microservices-consumer-movie-ribbon

# 命令执行超时时间，默认1秒
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
