management:
  health:
    mail:
      enabled: false

eureka:
  client:
    healthcheck:
      enabled: true 
    service-url:
#      defaultZone: http://user:psw123@localhost:8761/eureka 
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    # 默认是主机名:应用名:端口
    # 修改为应用名:端口
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
server:
  port: 7901

spring:
  application:
    name: microservices-consumer-movie # 名称建议用小写
    
# ribbon禁用eureka    
ribbon:
  eureka:
    enabled: false
microservices-provider-user:
  ribbon:
    listOfServers: localhost:7902,localhost:7900 # localhost:7900,localhost:7902 # (如果只配7900的话就只访问7900不访问7901)