server:
  port: 7901
spring:
  application:
    name: cinema
management:
  endpoint:
    health:
      show-details: always
  server:
    port: 17901
logging:
  level:
    root : INFO
    lqc.demo.springcloud.*: trace # 改成你的mapper文件所在包路径