server:
  port: 7903
spring:
  application:
    name: microservices-consumer-movie-feign
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 5000
feign.hystrix.enabled: true    
#management:
#  endpoints:
#    web:
#      base-path: /

# management.endpoint.health.show-details默认never，改为always显示全部信息
management:
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
