server:
  port: 8031
spring:
  application:
    name: turbine2
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}
turbine:
  aggregator:
    cluster-config:
    - default
  app-config: demo16-consumer-movie
  cluster-name-expression: "'default'" # 和new String("default")写法一样
#turbine.instanceUrlSuffix.demo16-consumer-movie: /actuator
